spring.application.name=pemudaprogrammer
spring.datasource.url=jdbc:postgresql://localhost:5432/pemudaprogrammerdb
spring.datasource.username=postgres
spring.datasource.password=1sampai10

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true